name: Check for updates
on:
  schedule:
    - cron: "33 * * * *"
  workflow_dispatch:
    inputs:
      force:
        description: "Force sync/generate dependency manifests"
        type: boolean
        required: true
        default: false
      version:
        description: "Sync specific version"
        type: string

env:
  NODE_VERSION: "18"
  JAVA_VERSION: "17"
jobs:
  check-update:
    runs-on: ubuntu-latest
    outputs:
      up_to_date: ${{ steps.check-update.outputs.up_to_date }}
    steps:
      - uses: actions/checkout@v3
      - name: Install xmllint tool
        run: |
          sudo apt-get update
          sudo apt-get install -y libxml2-utils
      - id: check-update
        run: ./00-check-update.sh
  flatpak-external-data-checker:
    runs-on: ubuntu-latest
    needs: [check-update]
    if: ${{ !needs.check-update.outputs.up_to_date || inputs.force }}
    steps:
      - uses: actions/checkout@v3
      - name: Install xmllint tool
        run: |
          sudo apt-get update
          sudo apt-get install -y libxml2-utils
      - name: Install Node.js, NPM and Yarn
        uses: actions/setup-node@v3
        with:
          node-version: ${{ env.NODE_VERSION }}
      - name: Install python and pix
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"
      - name: Setup Java SDK
        uses: actions/setup-java@v3
        with:
          distribution: "zulu"
          java-version: ${{ env.JAVA_VERSION }}
      - name: Setup clojure
        run: |
          curl -L -O https://github.com/clojure/brew-install/releases/latest/download/linux-install.sh
          chmod +x linux-install.sh
          ./linux-install.sh -p $HOME/.local
          echo "$HOME/.local/bin" >> $GITHUB_PATH
      - name: Install flatpak-node-generator
        run: pipx install "git+https://github.com/flatpak/flatpak-builder-tools.git#subdirectory=node"
      - name: Generate dependency manifests
        run: ./01-sync-release.sh ${{ inputs.version }}
      - name: Check files were correctly created
        run: ./02-check-release.sh
      - uses: docker://ghcr.io/flathub/flatpak-external-data-checker:latest
        env:
          GIT_AUTHOR_NAME: Flatpak External Data Checker
          GIT_COMMITTER_NAME: Flatpak External Data Checker
          GIT_AUTHOR_EMAIL: 41898282+github-actions[bot]@users.noreply.github.com
          GIT_COMMITTER_EMAIL: 41898282+github-actions[bot]@users.noreply.github.com
          EMAIL: 41898282+github-actions[bot]@users.noreply.github.com
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          args: --update --never-fork com.logseq.Logseq.yml
