name: Check for updates
on:
  schedule:
    - cron: '33 * * * *'
  workflow_dispatch:
    inputs:
      force:
        description: 'Force sync/generate dependency manifests'
        type: boolean
        required: true
        default: false
      version:
        description: 'Sync specific version'
        type: string

env:
  CLOJURE_VERSION: '1.11.1.1413'
  NODE_VERSION: '22'
  JAVA_VERSION: '11'
  PYTHON_VERSION: '3.11'
jobs:
  check-update:
    runs-on: ubuntu-latest
    outputs:
      up_to_date: ${{ steps.check-update.outputs.up_to_date }}
    steps:
      - uses: actions/checkout@v3
      - name: Install xmllint tool
        run: |
          sudo apt-get update
          sudo apt-get install -y libxml2-utils
      - id: check-update
        run: ./00-check-update.sh
  flatpak-external-data-checker:
    runs-on: ubuntu-latest
    needs: [ check-update ]
    if: ${{ !needs.check-update.outputs.up_to_date || inputs.force }}
    steps:
      - uses: actions/checkout@v3
      - name: Install xmllint tool
        run: |
          sudo apt-get update
          sudo apt-get install -y libxml2-utils
      - name: Install Node.js, NPM and Yarn
        uses: actions/setup-node@v3
        with:
          node-version: ${{ env.NODE_VERSION }}
      - name: Install python and pix
        uses: actions/setup-python@v4
        with:
          python-version: ${{ env.PYTHON_VERSION }}
      - name: Setup Java SDK
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: ${{ env.JAVA_VERSION }}
      - name: Setup clojure
        run: |
          curl -O -L https://download.clojure.org/install/linux-install-${{ env.CLOJURE_VERSION }}.sh
          sha256sum -c - <<HERE
          ad9aa1e99c59a4f7eb66450914fbec543337d9fada60dd9d34eec7fe18ae4965 linux-install-${{ env.CLOJURE_VERSION }}.sh
          HERE
          chmod +x linux-install-${{ env.CLOJURE_VERSION }}.sh
          ./linux-install-${{ env.CLOJURE_VERSION }}.sh -p $HOME/.local
          echo "$HOME/.local/bin" >> $GITHUB_PATH
      - name: Install flatpak-node-generator
        run: pipx install "git+https://github.com/flatpak/flatpak-builder-tools.git#subdirectory=node"
      - name: Generate dependency manifests
        run: ./01-sync-release.sh ${{ inputs.version }}
      - name: Check files were correctly created
        run: ./02-check-release.sh
      - uses: docker://ghcr.io/flathub/flatpak-external-data-checker:latest
        env:
          GIT_AUTHOR_NAME: Flatpak External Data Checker
          GIT_COMMITTER_NAME: Flatpak External Data Checker
          GIT_AUTHOR_EMAIL: 41898282+github-actions[bot]@users.noreply.github.com
          GIT_COMMITTER_EMAIL: 41898282+github-actions[bot]@users.noreply.github.com
          EMAIL: 41898282+github-actions[bot]@users.noreply.github.com
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          args: --update --never-fork com.logseq.Logseq.yml
